[platformio]
default_envs = esp32dev

[common]
lib_deps =
    knolleary/PubSubClient @ 2.8
    bblanchon/ArduinoJson @ 7.4.2
    ESP32Async/AsyncTCP @ 3.4.10
    ESP32Async/ESPAsyncWebServer @ 3.11.2
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -Wall
    -Wextra
    -Werror=return-type

[env:esp32dev]
platform = espressif32 @ 6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}
board_build.partitions = default.csv
upload_speed = 921600
check_skip_packages = yes

[env:esp32dev-debug]
extends = env:esp32dev
build_type = debug
build_flags =
    ${common.build_flags}
    -D CORE_DEBUG_LEVEL=4

[env:native]
platform = native
test_build_src = no
